

const MongoDb = () => {
    return (
        <div className=" ml-10 mr-10">

            <div>
            
            
            <h1 className=" text-[#47d4c2] text-center mb-10  text-7xl font-bold ">              
                   <span className=" text-green-600">MongoDB</span> interview Question
                  </h1>
                  <hr></hr>

{/* ----------------------------------------- */}
                 <div>


                         <p className=" mt-10  bg-[#30bdaa] p-3 rounded-xl text-xl font-bold">
                         Question 01 : What is MongoDB?
                         Answer        : MongoDB is a document-oriented database that stores data in flexible, JSON-like 
                         documents
                         </p>
                         <br></br>

                         <p className=" mt-10  bg-[#30bdaa] p-3 rounded-xl text-xl font-bold">
                         Question 02 : What is a Collection in MongoDB?
Answer        : A collection is a grouping of MongoDB documents. Documents within a collection 
                      can have different fields



                         </p>
                         <br></br>

                         <p className=" mt-10  bg-[#30bdaa] p-3 rounded-xl text-xl font-bold">
                         Question 03 : What is indexing in MongoDB?
Answer        : Indexing is the process of creating an index on a field in a MongoDB collection to 
                      improve query performance.


                         </p>
                         <br></br>

                         <p className=" mt-10  bg-[#30bdaa] p-3 rounded-xl text-xl font-bold">
                         Question 04 : Explain the Aggregation Framework in MongoDB.
Answer        : The Aggregation Framework is a powerful tool in MongoDB for data 
                      transformation and processing, allowing users to perform operations like filtering, 
                      grouping

                         </p>
                         <br></br>

                         <p className=" mt-10  bg-[#30bdaa] p-3 rounded-xl text-xl font-bold">
                         Question 05 : What is the significance of the ObjectId in MongoDB?
Answer        : ObjectId is a 12-byte identifier that is automatically generated by MongoDB and 
                      assigned to each document.

                         </p>
                         <br></br>

                         <p className=" mt-10  bg-[#30bdaa] p-3 rounded-xl text-xl font-bold">
                         Question 06 : What is the use of the findOne() method in MongoDB?
Answer        : The findOne() method is used to retrieve a single document from a collection that 
                      matches the specified query criteria.

                         </p>
                         <br></br>

                         <p className=" mt-10  bg-[#30bdaa] p-3 rounded-xl text-xl font-bold">
                         Question 07 : What is the significance of the ObjectId("...") method in MongoDB queries?
Answer        : The ObjectId("...") method is used to query documents based on their ObjectId.

                         </p>
                         <br></br>

                         <p className=" mt-10  bg-[#30bdaa] p-3 rounded-xl text-xl font-bold">
                         Question 08 : How to add and delete data in MongoDB?
Answer        : InsertOne,InsertMany method is for adding data and deleteOne, deleteMany
                      method is for deleting data in MongoDB.

                         </p>
                         <br></br>
                         
                         <p className=" mt-10  bg-[#30bdaa] p-3 rounded-xl text-xl font-bold">
                         Question 09 : What is aggregation in MongoDB?
Answer        :  Aggregation is a way of processing the large numbers of documents in collection 
		By means of passing them through different stages.

                         </p>
                         <br></br>

































                 </div>
 




            </div>
            
        </div>
    );
};

export default MongoDb;